### ISSUE TITLE
conftest verify does not support `--trace` flag

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#111]
As logged on the conftest slack channel by Grzegorz Głąb. Adding `--trace` support in running Rego tests with `conftest verify` would lead to a more consistent experience as the `conftest test` command also supports `--trace`.

The trace flag is already support by the [opa test runner](https://github.com/open-policy-agent/opa/blob/master/tester/runner.go), so it should be an easy include in the `conftest verify` command.

**Comment by menendezjaume** [comment]
I've had a look at [OPA test runner](https://github.com/open-policy-agent/opa/blob/0ed978c6889e45587253770d466cda9efd7da3ff/tester/runner.go#L137) and it is indeed quite easy to enable tracing. However: 

`EnableTracing enables tracing of evaluation and includes traces in results.`

This means that as well as capturing whether the user has added that flag or not, and pass it onto the runner, we would need to
- Capture the traces somehow in [runVerification](https://github.com/instrumenta/conftest/blob/8c9fc2bab1688be166b25a5fcebc7d6b3360e4b0/commands/verify/verify.go#L89)
- Tweak the handling of the results in [NewVerifyCommand:RunE](https://github.com/instrumenta/conftest/blob/8c9fc2bab1688be166b25a5fcebc7d6b3360e4b0/commands/verify/verify.go#L38). 

Since they both feed from the type [CheckResult](https://github.com/instrumenta/conftest/blob/309360dd6b7358d1b5c802e0b031708ebb345673/commands/test/test.go#L34), does that mean that we would need to modify it and add another element to the struct?

**Comment by Blokje5** [comment]
I am not sure if it is necessary to modify the `CheckResult` given that we would like to report the traces as either a success next to a succeeded test or a fail next to a failed test. The hard part is that this works well for JSON output and stdout output, but not with TAP output, although I can't imagine people will use trace and TAP at the same time.

There is a couple of approaches I could see:

1. We can return a formatted message which returns both the test result along with the traces. This then only handles the `verify` command output.
2. We output the traces before or after the test results.
3. We indeed change the CheckResult and allow for traces there, which might honestly be a nice solution, given that the `test` command also has a `--trace` flag. Given that this does not work with some formats, we can maybe warn when using `--trace` in combination with something like TAP, or just silently filter the traces and document the behaviour.

**Comment by menendezjaume** [comment]
Hey @Blokje5,
I gave it a go. I ended up modifying the `CheckResult` struct, which I thought was the neatest way to blend this feature with the exiting workflow. Please let me know what you think and if any changes are required. 
Thanks!

**Comment by menendezjaume** [comment]
I believe we can close this, right? I don't think I can do it myself.

**Comment by Blokje5** [comment]
Yes you are right. #163 is merged.
