### ISSUE TITLE
ConfigManager and different input types

### ISSUE THREAD

**Issue by jpreese** [instrumenta/conftest#158]
This is something thats been on my mind off and on, and wanted some feedback on.

Right now we use a single `ConfigManager` when a `conftest` command is run. Every file is parsed using the same input. But it feels like a good idea to support multiple. For example if we do:

`conftest test myyamlfile.yaml myjsonfile.json`

See line 180 in test.go
https://github.com/instrumenta/conftest/blob/master/commands/test/test.go#L180

`fileType` is set over and over again in the fileList loop, and the last one is used in the `ConfigManager`.

I don't want to get into implementation details necessarily, I already have some ideas there. The overall question is simply, do we want to support different input types in a single conftest command?

**Comment by Blokje5** [comment]
I like the idea, that makes it easier to work with a single conftest command, instead of having to run the test command for each format individually.

Also this would make it possible to verify multiple configuration types against each other. I could verify whether a database pointed to by a service in Kubernetes is created via Terraform, which could allow really powerful checks.

**Comment by boranx** [comment]
I also liked the idea. I had realized that when I'm combined two different files for `parse` command like:
```shell
 ./conftest parse examples/ini/grafana.ini examples/kubernetes/deployment.yaml
```
If you execute it, you'll see weird output for `ini`. This is obviously because of used `yaml` parser for `ini`.

**Comment by Blokje5** [comment]
@KeisukeYamashita added support for this with #195, I will close this issue.
