### ISSUE TITLE
getPolicyFiles does not accept non-Rego data files (i.e., YAML or JSON)

### ISSUE THREAD

**Issue by kmcquade** [instrumenta/conftest#169]
OPA proper loads any file that parses successfully as yaml or JSON (caveat being when --bundle params are used). However, conftest does not load non-rego files. Dove into the source code and saw this:

https://github.com/instrumenta/conftest/blob/master/policy/policy.go#L94

It would be great if this could be modified to accept YAML or JSON files. I struggled to identify an issue where my unit tests (run with `opa`) were passing, but when I would execute a policy with `conftest` against a real JSON file, it would fail. I put some example code [here](https://github.com/kmcquade/opa-terraform-exceptions-example#opa-terraform-exceptions-example
) to illustrate the issue. But of course, if you look at the policy.go file above, you'll see the root cause.

We want to use those YAML and JSON data files to specify exceptions to policies. If this issue were fixed in conftest, we could continue to use conftest while expressing exceptions to policies in some nice YAML. 

@garethr let me know if you have any questions.

**Comment by philjhale** [comment]
I've encountered this same issue with Conftest. I was trying to eliminate duplication between the error messages in my policies and in my unit tests. Here's a partial example (full example [here](https://github.com/philjhale/rego-examples/tree/master/terraform-conftest))

Policy file.
```
deny[msg] {
    changes := input.resource_changes[_] 
    changes.type == "google_project" 
    count(changes.change.after.name) > 30
    msg = sprintf(data.error_messages.project_name_too_long_msg, [changes.change.after.name])
}
```

Test.
```
test_project_name_too_long_denied {
    deny[sprintf(data.error_messages.project_name_too_long_msg, [input.resource_changes[_].change.after.name])] with input as { "resource_changes": [{ "type": "google_project", "change": { "after": { "name": "Test project whose name is too long" } } },{ "type": "google_project", "change": { "after": { "name": "Test project whose name is too long 2" } } }] }
}
```

Error messages JSON file.
```
{
    "error_messages" : {
        "project_name_too_long_msg": "Project '%s' name is too long"
    }
}
```

The unit test passes when executed with OPA. Running the Conftest `test` command always returns successfully, i.e. no output, regardless of whether the input is valid.

**Comment by kmcquade** [comment]
@jpreese @philjhale @Blokje5 @garethr - sorry to blow up everyone's notifications here! Just wondering if someone can take a look at this. :)

**Comment by Blokje5** [comment]
Yeah makes sense. We should make sure we load any data files as well into the modules.

**Comment by kmcquade** [comment]
Thank you @Blokje5 :)

**Comment by Blokje5** [comment]
Had a quick look: changing that line in the `policy.go` file does not work as that is indeed only looking for Rego files to compile. However, we can use the `rego.Load()` function in the `buildRego` function in the test command. 

The `rego.Load()` command will load any file with a *.rego, *.yaml, or *.json
extension. It could be a quick win to atleast make the `conftest test` command able to load `*.json` and `*.yaml` files. Sadly the same does not work for the Verify command as the test Runner struct from opa does not allow passing any rego funcs.

We can also move to using bundles but that means only `data.json` and `data.yaml` files can be found. I'll dive a bit deeper later on.

**Comment by patrick-east** [comment]
Thanks for looking into this @Blokje5 !

Just adding in my 2c... I fiddled around with similar things over the last few months with OPA CLI's so I figured I'd share.

Using `rego.Load()` is a pretty good option, and you can do something similar with `tester.Load()` to get a `storage.Store` and then pass it to the test runner via `Runner.SetStore(..)`.

Something to consider though that was (is) kind of a pain point for OPA eval/test/etc with the recursive data file loading vs bundle loading is that it was very easy for people to accidentally load in a bunch of additional yaml/json files that were not really intended. Most common issue being something like a workspace with k8s yaml manifests or like project json configs. If OPA tries to load them all and merge into the data document it will typically have conflicts and fail. This was confusing if someone just ran `opa test .` and then they see a "merge conflict" error.

We solved this over in OPA's CLI by starting down the path of pushing everyone to load things as bundles so it limits to the `data.json` and `data.yaml` files. The VSCode plugin defaults to this behavior now. A big driver for this approach was that we couldn't make a breaking change for the existing CLI behavior, so we added the new `--bundle`/`-b` flag.

With those points in mind, we maybe don't want to change the existing behavior for `--policy` to start pulling in any random yaml or json file, or even `data.yaml`/`data.json` files. The nice part is that since there is no existing behavior for loading data files we have some more flexibility to make something like a `--data` flag work more in a more graceful way.

If there are concerns about loading in random files then maybe consider the bundle style approach. Added benefit is that it would keep behavior more in line with where the OPA CLI's are going too. The main downside being that it means >1 way to load in rego files (bundles can contain both data and policy) which starts to make things complicated for users and maintainers. Thinking out loud.. could maybe make a `--data` flag load data files with the bundle semantics but ignore rego files, keeping them as only loaded from `--policy`. I think the opa `loader` package has all the API's required to do something like that.

**Comment by Blokje5** [comment]
Thanks for chiming in @patrick-east. It is really helpful to get some perspective of the issues encountered in the OPA CLI. I like the idea of adding a `--data` flag to keep it clean and avoid unexpected behaviour. I'll dive a bit deeper in the `loader` package. It would indeed be best if we avoid multiple mechanisms of loading policies.

**Comment by kmcquade** [comment]
@Blokje5 would this prevent me from loading multiple data.yaml files? If we had to specify `--data`, that would break the exceptions behavior, as shown in my example here: https://github.com/kmcquade/opa-terraform-exceptions-example

For example: Let's say that we have logic that prevents creation of security group rules for CIDR ranges that do not match either (1) RFC1918 CIDRs, (2) organization CIDRs, and (3) it can be updated periodically with static public IPs that are purchased. In this example, we don't want to have to update the Rego file all the time, or have developers push PRs in rego when they don't write in rego - we'd want them to make a PR to the YAML file. This way, there's a clear separation between the YAML files that contain the exceptions criteria, and the Rego files that contain the exceptions logic. Again, see the example.

Personally, I like things as-is with OPA w.r.t. the loading of non-rego files - we'd just like conftest to do the same :) 

Let me know what you think. Happy to answer any questions, and feel free to DM me over the OPA slack

**Comment by Blokje5** [comment]
@kmcquade I think building it in a way where we allow the `--data` flag to be passed multiple times makes sense. Indeed as you say, there are multiple use cases where this makes sense. The example you gave also provides a great test case for this change. I'll spend some time over the Christmas holiday to work on this. I'll keep everybody up to date on the progress.

**Comment by kmcquade** [comment]
@Blokje5 I think I didn't communicate our needs clearly. If we have to use the `--data` flag *multiple* times, that will create issues if we have a folder of files containing the exceptions data, as shown in my example. https://github.com/kmcquade/opa-terraform-exceptions-example/tree/master/policy

I think the `--data` flag in general is great. But it would help if we can do lazy loading, like being able to specify a folder path, rather than each individual data file.

Let me know if that makes sense.

**Comment by Blokje5** [comment]
@kmcquade Yes that makes total sense. Thanks for clarifying. It would be easy enough to extend the idea of specifying the `--data` flag multiple times to instead allow specification of a directory path. And I think that would be a great feature. We could even build in a default path (e.g. `policy/data`) to create a convention as to where to store the data and load that path by default (just like the `policy` dir is loaded by default).

**Comment by kmcquade** [comment]
That would be awesome. Thanks @Blokje5
