### ISSUE TITLE
Question: Are rules deny and warn really mandatory ?

### ISSUE THREAD

**Issue by rrey** [instrumenta/conftest#29]
Hello,

I am wondering if the rules being names `deny` and `warn` is mandatory ?
I've been first writing my policies with `opa` using the test framework available with it. It allows a TDD approach when writing the policies. 

When testing `conftest` (which have a better output for a CI integration), I have been kind of disappointed to see that all the rules should be named `deny` or `warn`, It forced me to rename my rules, and I am no more able to use `opa` tests anymore :/

Did I miss something ?
Would it be possible for `conftest` to look for rules through a regex ?
It would allow to write rules named `deny_some_explicit_name` or `warn_some_other_name` so that `conftest` finds the rules and one can still test the policies through `opa` test framework.

**Comment by garethr** [comment]
`opa test` is intended more for testing the Rego itself, rather than testing arbitrary input I think.

But I do like the idea of meaningful names. This will have a performance impact I think as each will be a separate query. I probably won't have time to implement this personally, but I'd be happy to see a PR explore the idea. Thanks for the feedback.

**Comment by garethr** [comment]
Thanks to @brendanjryan in #34 this is now in master.

**Comment by rrey** [comment]
Awesome !
