### ISSUE TITLE
Silent Error on Failed Test w/ Failed Rego

### ISSUE THREAD

**Issue by Salamandastron1** [instrumenta/conftest#51]
Conftest is silent, even on failing policy, with `sprintf` errors. For example:
```
deny["unable to find a gke container resource"] {
  not check_for_container_resources
}

check_for_container_resources {
    containers := [
      container |
      some i
      name := input.Resources[i].Name
      type := input.Resources[i].Type
      startswith(type, "google_container")
      container := type
    ]
    count(containers) == 2
}
```
results in exit 1

```
package main

deny[sprintf("unable to find a gke container resource %s %s", [input.Resources[i].Type, input.Resources[i].Name])] {
  not check_for_container_resources
}

check_for_container_resources {
    containers := [
      container |
      some i
      name := input.Resources[i].Name
      type := input.Resources[i].Type
      startswith(type, "google_container")
      container := type
    ]
    count(containers) == 2
} 
```
results in exit 0

**Comment by Blokje5** [comment]
Good find. It seems to be a harder problem then I anticipated it would be. Funnily enough when running master in debug mode the output is:

```bash
FATA[0000] Problem building rego compiler: stat examples/terraform/policy/gke.rego: no such file or directory 
```

which is exactly what you expect. `echo $?` returns 1 as well. However when compiling the docker image and running the same command (for reference I replaced the gke policy with the failing policy and run `conftest test -p examples/terraform/policy/gke.rego examples/terrafo
rm/gke.tf --debug`) I get exit status 0. I compiled conftest by changing the main func to the following

```golang
func main() {
	if err := commands.NewDefaultCommand().Execute(); err != nil {
		os.Exit(1)
	}
	fmt.Println("test")
}
```

which yields the following output:

```
examples/terraform/gke.tf
test
```

**Comment by Salamandastron1** [comment]
Interesting that it works differently on master vs image 🤔 Agreed that it is a big work around. I wish I had time to dig into it

**Comment by Blokje5** [comment]
It migth be related to differences in compiling. I run on a macbook pro 2017. It could also be a threading issue, something inside of the cobra package maybe? I'll mess with it some more.

**Comment by Blokje5** [comment]
Ok nvm debug failed because I can't read an error message. I messed up my debug configuration... 

However, it seems to be a problem with the policy itself: https://play.openpolicyagent.org/p/flCJB7Z6M1 does not return any message on deny.

The policy with a direct message in the deny rule returns a message: https://play.openpolicyagent.org/p/USsMjdM1Uy.

However, it will always return a message, even if the input is empty:
https://play.openpolicyagent.org/p/bVmqSSsjDr

I think the problem with the policy is that `not check_for_container_resources` always returns true unless you have exactly two resources of type container. The body of the deny rule evaluates to `true` meaning querying deny will return its output variable, which is the message.

**Comment by garethr** [comment]
Looks like this has a solution. Worth noting that the `--trace` can help in understanding what's happening with individual queries too.
