### ISSUE TITLE
Unclear error when providing file on -p

### ISSUE THREAD

**Issue by warmfusion** [instrumenta/conftest#6]
While the help documentation shows that the `-p` argument is meant to provide a directory path, the error message when giving an explicit filename is not clear;

```
$ conftest test -p specific_policy.rego file.yaml
FATA[0000] Problem building rego compiler: readdirent: invalid argument
```

Would it be possible either accept an explicit policy document as the argument, or make it clearer that the `-p` argument expects a _directory_ rather than a _file_ (or other type)

## Version

MacOS - 10.13.6

```
$ conftest --version
Version: 0.6.0
Commit: a27d0739a785fc52c421339d129267772a15662f
Date: 2019-05-20T07:40:07Z
```

**Comment by Blokje5** [comment]
@garethr I would like to pick up this issue. Would you like the approach where it is possible to specify a rego file instead of a directory on the flag? It might conflict with the pull command as the same flag is used to specify the directory to pull the policies too. Does it make sense to create a different flag to specify policy files?

**Comment by garethr** [comment]
@Blokje5 thanks! Mmm, good question. I can see pros and cons to both. On balance (and if you disagree say, as I changed my mind a few times) I think reusing `--policy` here is fine. I think it's reasonably unambiguously with `pull`, and if that turns out to be wrong I'm happy to break the UI at this early stage to correct obvious mistakes.

Any questions let me know.

**Comment by Blokje5** [comment]
I agree, it does not really conflict with the pull command and its use should be clear from the context. There is the issue with documenting the flag, as it is defined on the root cmd level. The current documentation specifies: "directory for Rego policy files". However, if you suddenly allow files for the test command the documentation would become a little more vague, something like this: "directory for Rego policy files. If a rego file is specified instead that policy is evaluated instead when running the test command. The pull and update commands expect a directory"
