### ISSUE TITLE
v0.13 - no warnings or fails with multi-file yamls

### ISSUE THREAD

**Issue by dewe** [instrumenta/conftest#95]
When upgrading from 0.11 to 0.13, conftest went silent. No warnings or failed tests.

```
# previously

$ brew switch conftest 0.11.0
$ conftest test deployment.yaml
FAIL - prometheus-adapter is running as root

# now

$ brew switch conftest 0.13.0
$ conftest test deployment.yaml

# silent...
```

I expected at least some output, not just silently passing all tests. 

```
$ conftest --version
Version: 0.13.0
Commit: 8340065
Date: 2019-09-27T22:40:00Z
```

**Comment by garethr** [comment]
Could you include the policy files and input file you're using?

**Comment by dewe** [comment]
Here goes: 

[files.zip](https://github.com/instrumenta/conftest/files/3676051/files.zip)

```bash
# in the folder
$ conftest test external-dns.yaml
```

**Comment by jpreese** [comment]
I looked into this some, and it looks like we broke multi-file yamls. In the provided example, if you remove all but the Deployment config, you'll get some results.

Since the yaml library doesn't support multi-document yaml files, we _were_ detecting line breaks/getting the result of each yaml in the `test.go` file. 

It looks like it was moved to the yaml parser itself.

At first glance, it doesn't look like the Rego evaluation isn't too happy with []interface{}.

**Comment by dewe** [comment]
Nice find. We’re using kustomize, so most of our configure are multi-document.

**Comment by amitsaha** [comment]
Ahh, didn;t realize this was a regression. I ran into this yesterday when feeding the output of `kustomize build` into `conftest test`. I even worked on "supporting it" (my WIP [here](https://github.com/instrumenta/conftest/compare/master...amitsaha:multidocument?expand=1)). 

My expectation of this feature is that it should consider the tests to be valid across all files in the multi-document YAML file.

**Comment by jpreese** [comment]
Well, it's a regression in the sense that multi-file yamls used to work. 0.13 appears to have broken that functionality.

**Comment by jpreese** [comment]
I have a PR out there that should resolve this.
